### ISSUE TITLE
Multiple primers per sample

### ISSUE THREAD

**Issue by Fred-White94** [a-h-b/dadasnake#11]
Hi, I have an ITS dataset with multiple forward and reverse primers per sample. Is it possible to add multiple (slightly different) primers to the config file and if so how should that be formatted?

**Comment by a-h-b** [comment]
Hi, can you specify how the primers are different? is it possible to summarize them as one set of degenerate primers? do they bind at the same positions? 
-AHB

**Comment by Fred-White94** [comment]
Hi, thanks for getting back so quickly. They are indeed a degenerate set with the last bases being identical to those in config.ITS1

**Comment by a-h-b** [comment]
you can give the degenerate sequence in the config file, then. Or am I missing something?

**Comment by Fred-White94** [comment]
Sorry - first time analysing ITS data (and not my dataset)
The primers have identical adapters (of course) followed by 1-3 additional nucleotides followed by the identical primer sequence so perhaps not "degenerate"

ACACTGACGACATGGTTCTACA                CTTGGTCATTTAGAGGAAGTAA;
ACACTGACGACATGGTTCTACA    T          CTTGGTCATTTAGAGGAAGTAA;
ACACTGACGACATGGTTCTACA   AC        CTTGGTCATTTAGAGGAAGTAA;
ACACTGACGACATGGTTCTACA  CTA       CTTGGTCATTTAGAGGAAGTAA;

The question is how do I incorporate the extra potential letters between adapter and primer. Hope this is clear.

Thanks you

**Comment by a-h-b** [comment]
you can just put the CTTGGTCATTTAGAGGAAGTAA in the config file. The primer step searches for this part and cuts it and the adapter off.

**Comment by Fred-White94** [comment]
Ok thanks for the quick solve!

**Comment by a-h-b** [comment]
you're welcome. Let me know if you run into any problems.
-AHB

**Comment by thierryjanssens** [comment]
Hi all,

what about incorporating multiple primer set from a multiplex approach  (i.e. different genes/regions)?

Activating conda environment: /home/minion/git/dadasnake/conda/cb1403239da0c2b661e2126fd0da49e1
[Tue Dec 14 16:08:35 2021]
Error in rule primer_numbers:
    jobid: 16
    output: reporting/primerNumbers_perLibrary.tsv, reporting/primerNumbers_perSample.tsv
    log: logs/countPrimerReads.log (check log file(s) for error message)
    conda-env: /home/minion/git/dadasnake/conda/cb1403239da0c2b661e2126fd0da49e1
