### ISSUE TITLE
VARIABLE_CONFIG?

### ISSUE THREAD

**Issue by marwa38** [a-h-b/dadasnake#17]
_SCHEDULER - insert the name of the scheduler you want to use (currently slurm or uge). This determines the cluster config given to snakemake, e.g. the cluster config file for slurm is config/slurm.config.yaml . Also check that the settings in this file is correct. If you have a different system, contact us ( https://github.com/a-h-b/dadasnake/issues )._

re the above quote, you kindly mentioned to contact you in case I am not using slurm, I am on ubuntu (server name is calling) so what should I write down in the config file under SCHEDULER?

-----------
_SUBMIT_COMMAND - insert the bash command you'll usually use to submit a job to your cluster to run on a single cpu for a few days. You only need this, if you want to have the snakemake top instance running in a submitted job. You alternatively have the option to run it on the frontend via tmux. Leave empty, if you want to use this frontend version and have tmux installed._

I won't use tmux and I will be using the code (nice -n 19 .....) to invoke snakemake under  SUBMIT_COMMAND in case needed? or it is fine to add 19 under MAX_THREADS otherwise?

**Comment by a-h-b** [comment]
Thanks for your question.
If I got you right, you don't actually use a scheduler. So, you don't need to fill anything under either SCHEDULER or SUBMIT_COMMAND. If you run dadasnake, you need to give it the -l option. This way, all the commands are run in the session you used to submit. If you want to make use of more than one thread/core, you can also use the -t option, e.g. -t 4 . I hope this helps. Let me know if it works-
AHB

**Comment by a-h-b** [comment]
I've updated the readme to answer this, so I'll close the issue now.
