### ISSUE TITLE
Visualize DAG

### ISSUE THREAD

**Issue by thierryjanssens** [a-h-b/dadasnake#24]
How can I visualize the workflow of dadasnake? This would allow me to get an insight in the separate processes of the pipeline.

I do not succeed in creating a dag file with the snakemake --dag option with the dadasnake wrapper.

**Comment by a-h-b** [comment]
Hi -
you need to call snakemake directly. 
DIR: path to your dadasnake directory
CONFIG: path to your config file

you may also have to activate the conda environment with snakemake first 
If you followed the normal install instructions, it sits here:

```
conda activate $DIR/conda/snakemake_env

snakemake --cores 1 -s $DIR/Snakefile --dag --configfile $CONFIGFILE --use-conda --conda-prefix $DIR/conda
```
also mind the description [here](https://snakemake.readthedocs.io/en/v5.1.4/executable.html#visualization) about visualization.

Hope this helps -
A

**Comment by thierryjanssens** [comment]
Hi,

yes this help.
But converting it to a pdf does not work.

$ cat dag | dot -Tpdf > dag.pdf
Error: <stdin>: syntax error in line 1 near 'laptop'

Somewhere an undesired print statement gets introduced. It is not coming from the main Snaekfile apparently. Maybe some of the smk modules?

**Comment by a-h-b** [comment]
Hi, I am sorry, but for the time being, you need to catch those prints with grep -v , as in 

`snakemake --cores 1 -s $DIR/Snakefile --dag --configfile $CONFIGFILE --use-conda --conda-prefix $DIR/conda | grep -v laptop | grep "Final" -v | grep "maxCores" -v | dot -Tpdf > dag.pdf`

you may have to add more. Alternatively, you can do

`snakemake --cores 1 -s $DIR/Snakefile --dag --configfile $CONFIGFILE --use-conda --conda-prefix $DIR/conda >> my_dag.txt`

then you can edit this file and remove all lines before `digraph snakemake_dag {`

then you pipe that file to dot

`cat my_dag.txt  | dot -Tpdf > dag.pdf`

hope this helps -
A

**Comment by a-h-b** [comment]
if the pipeline ran successfully, you can of course also use `dadasnake -r $CONFIG` , which will create a .html report, which contains the tree.

**Comment by thierryjanssens** [comment]
Ok, thank you.
This is very helpfull.
I need the DAG for debugging and to try to find my way in the dadasnake workflow..
