### ISSUE TITLE
error: "Could not create conda environment from ... "

### ISSUE THREAD

**Issue by gljessen** [a-h-b/dadasnake#27]
Hey there, 
(problem)
(Mac OS) having an error after step 6 of the Dadasnake tutorial; "Initialize conda environments: This run sets up the conda environments that will be usable by all users:"

when running: 
`./dadasnake -i config/config.init.yaml` 

I get the following error message:
Initializing conda environments.
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

Then runs and crashes into: 
CreateCondaEnvironmentException:
Could not create conda environment from /Users/.....

I have tried reinstalling everything and removing environments, also changing shell
`conda init bash` or `conda init zsh` but the error persists. Moreover, a new set of "Encountered problems while solving:" appeared each time. 

Thanks!

Screenshot:
[image](https://freeimage.host/i/XPBFqB)

**Comment by pommesjet** [comment]
Try navigating to the folder and manually deleting the tensorflow-gpu folder then try again

**Comment by gljessen** [comment]
That doesn't makes any sense

**Comment by gljessen** [comment]
> Hi - it's possible that it just doesn't install on Mac, because the conda packages don't always all work on mac. Give me a couple of days to check, if I can find versions that do. But yeah, if you've got a linux machine, that would solve it. Best wishes - AHB

much appreciated

**Comment by a-h-b** [comment]
Hi - I've had a look, but I also can't seem to get the conda installations to work on mac. Do you have access to a linux machine? -AHB

**Comment by gljessen** [comment]
Thank you, yes at the end I'm working on the server only.
Thanks again!
