### ISSUE TITLE
WorkflowError: File reporting/primerNumbers_perLibrary.tsv marked for report but does not exist.

### ISSUE THREAD

**Issue by tboonf** [a-h-b/dadasnake#33]
I have installed the program and have  no issue in running the rest run. However, when i tried to run test dataset using config.16S.yaml, I was prompted with the error message as above. I have modified the config file in the section of raw and output directory, as well as the database for Silva. Complete error message is below:

Building DAG of jobs...
Creating report...
Missing metadata for file workflow.done. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file primers.done. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file preprocessing/2/sample_2.fwd.fastq.gz. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
WorkflowError:
File reporting/primerNumbers_perLibrary.tsv marked for report but does not exist.

Please help.

**Comment by a-h-b** [comment]
Hi - thanks for reaching out. Can you let me know the command you used for starting this?
Best wishes -
AHB

**Comment by tboonf** [comment]
This is the command i used: ./dadasnake -n "TESTRUN2" -r config/config.16S.yaml

**Comment by a-h-b** [comment]
oh, yes only run reporting... you need to include -c or -f or -l to actually run the pipeline (see ./dadasnake -h).

**Comment by tboonf** [comment]
Thank you. Now that has been resolved. Very helpful.
I have gone ahead and tried using my own data. All went well until i received this error message:
Error in rule dada_dadaSingle_pool:
    jobid: 12
    output: merged/dada_merged.RDS
    log: logs/DADA2_read2RDS.log (check log file(s) for error message)


When I checked the log file, this was what described:
"Error in dada_uniques(names(drpi$uniques), unname(drpi$uniques), names(drpi$uniques) %in%  : 
  Rounded quality exceeded range of err lookup table."

Would appreciate any help to resolve this.
Thank you :-)

**Comment by a-h-b** [comment]
Hi, okay, so that's a new error... what kind of data do you have? (as in, what kind of quality values do you expect?

**Comment by tboonf** [comment]
It’s nanopore data

**Comment by a-h-b** [comment]
oh, okay... it doesn't do that (except if you did a pre-processing like in here: [10.1093/gigascience/giy140](https://doi.org/10.1093/gigascience/giy140)) , sorry. Or you can ignore the quality values, but that may not be a good choice...
